In [20]:
from pathlib import Path
import json
import pandas as pd

In [52]:
hathi_metadata = pd.read_csv("../data/hathimeta/titlemeta.tsv", sep="\t")
hathi_metadata.loc[:, "book_id"] = hathi_metadata.docid.apply(lambda x: x + ".clean")
hathi_metadata = hathi_metadata.set_index("book_id")

/tmp/ipykernel_891196/3717131593.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  hathi_metadata = pd.read_csv("../data/hathimeta/titlemeta.tsv", sep="\t")

In [55]:
def debug_entity(book_id, character_id):
    booknlp_dir = Path("../data/booknlp/")
    meta = hathi_metadata.loc[book_id]
    meta_book = json.load(open(booknlp_dir / f"{book_id}/{book_id}.book"))
    entity_to_g = {
        entity["id"]: (entity["g"], entity["mentions"])
        for entity in meta_book["characters"]
        if entity["g"] is not None
    }
    entities_book = pd.read_csv(
        booknlp_dir / f"{book_id}/{book_id}.entities", sep="\t", quoting=3
    )

    print(meta.title)
    print(entities_book[entities_book.COREF.eq(character_id)])
    print(entity_to_g[character_id])

In [58]:
debug_entity("wu.89099779167.clean", 267)

David Armstrong, or, Before the dawn : | a novel.
       COREF  start_token  end_token  prop  cat          text
662      267         4646       4646  PROP  PER         Deeta
663      267         4650       4650  PROP  PER         Deeta
670      267         4738       4738  PROP  PER         David
687      267         4866       4867  PROP  PER  little Deeta
688      267         4874       4874  PROP  PER         David
...      ...          ...        ...   ...  ...           ...
12375    267        93496      93496  PRON  PER           She
12391    267        93642      93642  PROP  PER         Deeta
12395    267        93658      93658  PROP  PER         David
12412    267        93743      93744  PROP  PER    Poor David
12414    267        93749      93749  PROP  PER         Deeta

[1222 rows x 6 columns]
({'inference': {'he/him/his': 0.397, 'she/her': 0.56, 'they/them/their': 0.036, 'xe/xem/xyr/xir': 0.003, 'ze/zem/zir/hir': 0.003}, 'argmax': 'she/her', 'max': 0.56, 'total': 265.359}, {'proper': [{'c': 216, 'n': 'Deeta'}, {'c': 162, 'n': 'David'}, {'c': 15, 'n': 'Davie'}, {'c': 12, 'n': 'little Deeta'}, {'c': 2, 'n': 'Little Deeta'}, {'c': 1, 'n': 'Deeta David'}, {'c': 1, 'n': 'whitner Deeta'}, {'c': 1, 'n': 'old David'}, {'c': 1, 'n': 'poor trembling little Deeta'}, {'c': 1, 'n': 'poor little Deeta'}, {'c': 1, 'n': 'old Davie'}, {'c': 1, 'n': 'poor David'}, {'c': 1, 'n': 'little provincial Deeta'}, {'c': 1, 'n': 'Poor David'}], 'common': [], 'pronoun': [{'c': 342, 'n': 'her'}, {'c': 223, 'n': 'she'}, {'c': 59, 'n': 'you'}, {'c': 55, 'n': 'She'}, {'c': 40, 'n': 'I'}, {'c': 20, 'n': 'herself'}, {'c': 19, 'n': 'me'}, {'c': 10, 'n': 'You'}, {'c': 7, 'n': 'your'}, {'c': 5, 'n': 'Her'}, {'c': 4, 'n': 'ye'}, {'c': 4, 'n': 'yourself'}, {'c': 4, 'n': 'my'}, {'c': 2, 'n': "ye're"}, {'c': 2, 'n': 'hers'}, {'c': 2, 'n': 'himself'}, {'c': 1, 'n': 'i'}, {'c': 1, 'n': "ye'll"}, {'c': 1, 'n': 'mine'}, {'c': 1, 'n': 'My'}, {'c': 1, 'n': 'j'}, {'c': 1, 'n': 'yer'}, {'c': 1, 'n': '1'}, {'c': 1, 'n': 'sheleft'}]})

In [57]:
debug_entity("hvd.hxj2ez.clean", 4728)

A complete collection of state trials | and proceedings for high treason and other crimes and misdemeanors ... : with notes and other illustrations / | $c: compiled by T.B. Howell.
        COREF  start_token  end_token  prop  cat                   text
105267   4728       766731     766732  PROP  PER             Miss Clark
105299   4728       766901     766904  PROP  PER  the artful Miss Clark
105327   4728       767046     767047  PROP  PER             Miss Clark
106012   4728       774422     774422  PROP  PER                Depones
106018   4728       774458     774459  PROP  PER             Miss Clark
...       ...          ...        ...   ...  ...                    ...
110736   4728       804419     804419  PROP  PER                Ogilvie
110761   4728       804542     804542  PROP  PER                Depones
110775   4728       804605     804605  PROP  PER                Depones
110813   4728       804866     804866  PROP  PER                Depones
110977   4728       806052     806052  PROP  PER                Depones

[288 rows x 6 columns]
({'inference': {'he/him/his': 0.75, 'she/her': 0.158, 'they/them/their': 0.092, 'xe/xem/xyr/xir': 0.0, 'ze/zem/zir/hir': 0.0}, 'argmax': 'he/him/his', 'max': 0.75, 'total': 100064.942}, {'proper': [{'c': 118, 'n': 'Depones'}, {'c': 27, 'n': 'Ogilvie'}, {'c': 19, 'n': 'Miss Clark'}, {'c': 8, 'n': 'lieutenant Ogilvie'}, {'c': 4, 'n': 'Clark'}, {'c': 1, 'n': 'the artful Miss Clark'}, {'c': 1, 'n': 'sbe Depones'}, {'c': 1, 'n': 'an Ogilvie'}, {'c': 1, 'n': 'ibe Depones'}, {'c': 1, 'n': 'lieutenant Ogilvie ( who is above de Depones , that soon thereafter Miss Clark , in signed captaiu'}, {'c': 1, 'n': 'de Depones'}, {'c': 1, 'n': 'Ogilvie pannel'}], 'common': [], 'pronoun': [{'c': 68, 'n': 'he'}, {'c': 20, 'n': 'his'}, {'c': 15, 'n': 'him'}, {'c': 1, 'n': 'himself'}, {'c': 1, 'n': 'be'}]})

In [64]:
debug_entity("mdp.39015064003018.clean", 0)

The novels and romances of Anna Eliza Bray ...
       COREF  start_token  end_token  prop  cat text
1          0           25         25  PRON  PER    I
30         0          350        350  PRON  PER   me
47         0          440        440  PRON  PER   My
49         0          450        450  PRON  PER    I
54         0          469        469  PRON  PER    I
...      ...          ...        ...   ...  ...  ...
33704      0       241263     241263  PRON  PER   me
33711      0       241322     241322  PRON  PER    I
33712      0       241336     241336  PRON  PER    I
33713      0       241343     241343  PRON  PER   my
33716      0       241351     241351  PRON  PER    I

[3245 rows x 6 columns]
({'inference': {'he/him/his': 0.68, 'she/her': 0.189, 'they/them/their': 0.105, 'xe/xem/xyr/xir': 0.009, 'ze/zem/zir/hir': 0.016}, 'argmax': 'he/him/his', 'max': 0.68, 'total': 502.558}, {'proper': [], 'common': [], 'pronoun': [{'c': 1686, 'n': 'I'}, {'c': 761, 'n': 'my'}, {'c': 518, 'n': 'me'}, {'c': 57, 'n': 'myself'}, {'c': 49, 'n': 'My'}, {'c': 45, 'n': 'he'}, {'c': 35, 'n': 'you'}, {'c': 28, 'n': 'his'}, {'c': 15, 'n': 'him'}, {'c': 14, 'n': 'mine'}, {'c': 10, 'n': 'He'}, {'c': 8, 'n': 'your'}, {'c': 6, 'n': 'i'}, {'c': 3, 'n': 'I.'}, {'c': 3, 'n': 'Your'}, {'c': 2, 'n': 'yourself'}, {'c': 2, 'n': 'You'}, {'c': 1, 'n': 'himself'}, {'c': 1, 'n': 'Mine'}, {'c': 1, 'n': 'thee'}]})

In [60]:
debug_entity("wu.89098013634.clean", 49)

A little princess; | being the whole story of Sara Crewe, now told for the first time, | $c: by Frances Hodgson Burnett; with illustrations in colors by Ethel Franklin Betts.
Empty DataFrame
Columns: [COREF, start_token, end_token, prop, cat, text]
Index: []

KeyError: 885339

       COREF  start_token  end_token  prop  cat           text
74702   2862       422728     422729  PROP  PER  Darling Rosey
74704   2862       422741     422741  PRON  PER            her
74835   2862       423544     423544  PROP  PER          Rosey
74836   2862       423550     423550  PRON  PER            She
74837   2862       423560     423560  PRON  PER            her
74838   2862       423567     423567  PRON  PER            her
74839   2862       423573     423573  PRON  PER            She
74840   2862       423579     423579  PRON  PER            her
74842   2862       423582     423582  PRON  PER            her

In [18]:
meta_book["characters"][887]["id"]

2862

In [17]:
meta_book["characters"][887]["g"]

{'inference': {'he/him/his': 0.225,
  'she/her': 0.693,
  'they/them/their': 0.05,
  'xe/xem/xyr/xir': 0.016,
  'ze/zem/zir/hir': 0.016},
 'argmax': 'she/her',
 'max': 0.693,
 'total': 12.651}

In [16]:
meta_book["characters"][887]["mentions"]

{'proper': [{'c': 1, 'n': 'Darling Rosey'}, {'c': 1, 'n': 'Rosey'}],
 'common': [],
 'pronoun': [{'c': 5, 'n': 'her'}, {'c': 2, 'n': 'She'}]}

In [27]:
entity_to_g[2862]

{'inference': {'he/him/his': 0.225,
  'she/her': 0.693,
  'they/them/their': 0.05,
  'xe/xem/xyr/xir': 0.016,
  'ze/zem/zir/hir': 0.016},
 'argmax': 'she/her',
 'max': 0.693,
 'total': 12.651}

In [33]:
from fashion.sources import HathiAll

In [39]:
book_id = "chi.14533347.clean"
tokens_book = pd.read_csv(
    booknlp_dir / f"{book_id}/{book_id}.tokens",
    sep="\t",
    quoting=3,  # 3 = csv.QUOTE_NONE
).set_index("token_ID_within_document")

# calculate sentence start and end indices
tokens_book["sentence_start"] = tokens_book.groupby(
    "sentence_ID"
).byte_onset.transform("min")
tokens_book["sentence_end"] = tokens_book.groupby(
    "sentence_ID"
).byte_offset.transform("max")

tokens_book["sentence_has_adjectives"] = tokens_book.groupby(
    "sentence_ID"
).POS_tag.transform(lambda x: x.eq("ADJ").any())

# get character mentions
entities_book = pd.read_csv(
    booknlp_dir / f"{book_id}/{book_id}.entities", sep="\t", quoting=3
)

meta_book = json.load(open(booknlp_dir / f"{book_id}/{book_id}.book"))
entity_to_g = {
    entity["id"]: entity["g"]
    for entity in meta_book["characters"]
    if entity["g"] is not None
}

# merge character mentions with token offsets
entities_book = entities_book.merge(
    tokens_book[["byte_onset", "sentence_start", "sentence_has_adjectives"]],
    left_on="start_token",
    right_index=True,
)
entities_book = entities_book.merge(
    tokens_book[["byte_offset", "sentence_end"]],
    left_on="end_token",
    right_index=True,
)
entities_book = entities_book.rename(
    columns={
        "byte_onset": "entity_start_idx",
        "byte_offset": "entity_end_idx",
    }
)

entities_book = entities_book[
    # entities_book.COREF.astype(str).isin(entity_corefs)
    True
    & entities_book.sentence_has_adjectives
    & entities_book.cat.eq("PER")
]
# filename,sentence,term,start_idx,end_idx,sentence_start_idx,sentence_end_idx

book = HathiAll().load_text(book_id)

if entities_book.empty:
    print(f"No entities found for book {book_id}. Skipping.")

try:
    entities_book["sentence"] = entities_book[
        ["sentence_start", "sentence_end"]
    ].apply(lambda x: book.text[x.sentence_start : x.sentence_end], axis=1)
except Exception as e:
    print(f"Error processing book {book_id}: {e}")

entities_book["term"] = entities_book[
    ["entity_start_idx", "entity_end_idx"]
].apply(lambda x: book.text[x.entity_start_idx : x.entity_end_idx], axis=1)

entities_book = entities_book.drop_duplicates(subset=["COREF", "sentence"])

output_df = pd.DataFrame(
    {
        "mention_id": entities_book.COREF,
        "filename": book_id,
        "sentence": entities_book.sentence,
        "term": entities_book.term,
        "start_idx": entities_book.entity_start_idx
        - entities_book.sentence_start,
        "end_idx": entities_book.entity_end_idx - entities_book.sentence_start,
        "sentence_start_idx": entities_book.sentence_start,
        "sentence_end_idx": entities_book.sentence_end,
        "gender": entities_book.COREF.apply(
            lambda x: entity_to_g[x]["argmax"] if x in entity_to_g else None
        ),
    }
)

In [40]:
entities_book[entities_book.COREF.eq(209)]

,COREF,start_token,end_token,prop,cat,text,entity_start_idx,sentence_start,sentence_has_adjectives,entity_end_idx,sentence_end,sentence,term
2884,209,26297,26297,PROP,PER,SNOWDROP,114763,114568,True,114771,114772,"My ladies stared, and not a word \nDid they ad...",SNOWDROP
2885,209,26300,26301,PROP,PER,Miss Snowdrop,114780,114774,True,114793,114865,ITTLE Miss Snowdrop \nHas come over the way; \...,Miss Snowdrop
2892,209,26371,26373,PROP,PER,Little Miss Snowdrop,115091,115091,True,115111,115240,"Little Miss Snowdrop, \nSo brave and so true, ...",Little Miss Snowdrop
2896,209,26426,26426,PRON,PER,her,115314,115267,True,115317,115354,"COME, little bee, to the wild rose cup; \nBrin...",her
2906,209,26595,26595,PRON,PER,her,116128,116107,True,116131,116228,"Then wild rose swung her censer, \nAnd, in a s...",her

In [41]:
output_df[output_df.mention_id.eq(209)]

,mention_id,filename,sentence,term,start_idx,end_idx,sentence_start_idx,sentence_end_idx,gender
2884,209,chi.14533347.clean,"My ladies stared, and not a word \nDid they ad...",SNOWDROP,195,203,114568,114772,she/her
2885,209,chi.14533347.clean,ITTLE Miss Snowdrop \nHas come over the way; \...,Miss Snowdrop,6,19,114774,114865,she/her
2892,209,chi.14533347.clean,"Little Miss Snowdrop, \nSo brave and so true, ...",Little Miss Snowdrop,0,20,115091,115240,she/her
2896,209,chi.14533347.clean,"COME, little bee, to the wild rose cup; \nBrin...",her,47,50,115267,115354,she/her
2906,209,chi.14533347.clean,"Then wild rose swung her censer, \nAnd, in a s...",her,21,24,116107,116228,she/her