In [20]:
from pathlib import Path
import json
import pandas as pd

In [43]:
def debug_entity(book_id, character_id):
    booknlp_dir = Path("../data/booknlp/")
    meta_book = json.load(open(booknlp_dir / f"{book_id}/{book_id}.book"))
    entity_to_g = {
        entity["id"]: (entity["g"], entity["mentions"])
        for entity in meta_book["characters"]
        if entity["g"] is not None
    }
    entities_book = pd.read_csv(
        booknlp_dir / f"{book_id}/{book_id}.entities", sep="\t", quoting=3
    )
    
    print(entities_book[entities_book.COREF.eq(character_id)])
    print(entity_to_g[character_id])

In [29]:
debug_entity("chi.14533347.clean", 209)

      COREF  start_token  end_token  prop  cat                  text
2884    209        26297      26297  PROP  PER              SNOWDROP
2885    209        26300      26301  PROP  PER         Miss Snowdrop
2886    209        26308      26308  PRON  PER                   She
2887    209        26320      26321  PROP  PER         Miss Snowdrop
2889    209        26358      26358  PRON  PER                   her
2890    209        26361      26361  PRON  PER                   She
2891    209        26364      26364  PRON  PER                   her
2892    209        26371      26373  PROP  PER  Little Miss Snowdrop
2895    209        26403      26403  PRON  PER                     I
2896    209        26426      26426  PRON  PER                   her
2906    209        26595      26595  PRON  PER                   her
{'inference': {'he/him/his': 0.136, 'she/her': 0.808, 'they/them/their': 0.055, 'xe/xem/xyr/xir': 0.0, 'ze/zem/zir/hir': 0.0}, 'argmax': 'she/her', 'max': 0.808, 'total': 200001.5}

In [45]:
debug_entity("hvd.hxj2ez.clean", 4728)

        COREF  start_token  end_token  prop  cat                   text
105267   4728       766731     766732  PROP  PER             Miss Clark
105299   4728       766901     766904  PROP  PER  the artful Miss Clark
105327   4728       767046     767047  PROP  PER             Miss Clark
106012   4728       774422     774422  PROP  PER                Depones
106018   4728       774458     774459  PROP  PER             Miss Clark
...       ...          ...        ...   ...  ...                    ...
110736   4728       804419     804419  PROP  PER                Ogilvie
110761   4728       804542     804542  PROP  PER                Depones
110775   4728       804605     804605  PROP  PER                Depones
110813   4728       804866     804866  PROP  PER                Depones
110977   4728       806052     806052  PROP  PER                Depones

[288 rows x 6 columns]
({'inference': {'he/him/his': 0.75, 'she/her': 0.158, 'they/them/their': 0.092, 'xe/xem/xyr/xir': 0.0, 'ze/zem/zir/hir': 0.0}, 'argmax': 'he/him/his', 'max': 0.75, 'total': 100064.942}, {'proper': [{'c': 118, 'n': 'Depones'}, {'c': 27, 'n': 'Ogilvie'}, {'c': 19, 'n': 'Miss Clark'}, {'c': 8, 'n': 'lieutenant Ogilvie'}, {'c': 4, 'n': 'Clark'}, {'c': 1, 'n': 'the artful Miss Clark'}, {'c': 1, 'n': 'sbe Depones'}, {'c': 1, 'n': 'an Ogilvie'}, {'c': 1, 'n': 'ibe Depones'}, {'c': 1, 'n': 'lieutenant Ogilvie ( who is above de Depones , that soon thereafter Miss Clark , in signed captaiu'}, {'c': 1, 'n': 'de Depones'}, {'c': 1, 'n': 'Ogilvie pannel'}], 'common': [], 'pronoun': [{'c': 68, 'n': 'he'}, {'c': 20, 'n': 'his'}, {'c': 15, 'n': 'him'}, {'c': 1, 'n': 'himself'}, {'c': 1, 'n': 'be'}]})

In [50]:
debug_entity("uva.x030576612.clean", 601)

       COREF  start_token  end_token  prop  cat   text
1087     601         9370       9370   NOM  PER  Madam
1091     601         9406       9406  PRON  PER    she
1201     601         9950       9950   NOM  PER  madam
1204     601         9964       9964  PRON  PER   your
1206     601         9973       9973  PRON  PER    she
...      ...          ...        ...   ...  ...    ...
22542    601       143558     143558   NOM  PER  Madam
22555    601       143622     143622   NOM  PER  Madam
22594    601       143803     143803   NOM  PER  madam
23185    601       146965     146965   NOM  PER  madam
23202    601       147039     147039   NOM  PER  madam

[229 rows x 6 columns]
({'inference': {'he/him/his': 0, 'she/her': 1.0, 'they/them/their': 0, 'xe/xem/xyr/xir': 0, 'ze/zem/zir/hir': 0}, 'argmax': 'she/her', 'max': 1.0, 'total': 22}, {'proper': [], 'common': [{'c': 49, 'n': 'madam'}, {'c': 28, 'n': 'Madam'}], 'pronoun': [{'c': 66, 'n': 'you'}, {'c': 43, 'n': 'your'}, {'c': 13, 'n': 'she'}, {'c': 8, 'n': 'her'}, {'c': 7, 'n': 'I'}, {'c': 7, 'n': 'You'}, {'c': 3, 'n': 'yourself'}, {'c': 1, 'n': 'my'}, {'c': 1, 'n': 'herself'}, {'c': 1, 'n': 'Your'}, {'c': 1, 'n': 'yours'}, {'c': 1, 'n': 'She'}]})

In [49]:
debug_entity("uva.x030576612.clean", 0)

       COREF  start_token  end_token  prop  cat text
3          0           10         10  PRON  PER    i
5          0           46         46  PRON  PER    I
365        0         4018       4018  PRON  PER    I
395        0         4309       4309  PRON  PER   me
396        0         4325       4325  PRON  PER   me
...      ...          ...        ...   ...  ...  ...
24072      0       152104     152104  PRON  PER   he
24135      0       152497     152497  PRON  PER    I
24136      0       152500     152500  PRON  PER   my
24138      0       152503     152503  PRON  PER    I
24140      0       152508     152508  PRON  PER   my

[1797 rows x 6 columns]
({'inference': {'he/him/his': 0.56, 'she/her': 0.227, 'they/them/their': 0.161, 'xe/xem/xyr/xir': 0.02, 'ze/zem/zir/hir': 0.032}, 'argmax': 'he/him/his', 'max': 0.56, 'total': 228.399}, {'proper': [], 'common': [], 'pronoun': [{'c': 964, 'n': 'I'}, {'c': 326, 'n': 'my'}, {'c': 236, 'n': 'me'}, {'c': 74, 'n': 'he'}, {'c': 46, 'n': 'you'}, {'c': 33, 'n': 'myself'}, {'c': 27, 'n': 'his'}, {'c': 20, 'n': 'My'}, {'c': 18, 'n': 'your'}, {'c': 18, 'n': 'him'}, {'c': 6, 'n': 'i'}, {'c': 6, 'n': 'himself'}, {'c': 5, 'n': 'He'}, {'c': 4, 'n': 'You'}, {'c': 3, 'n': 'mine'}, {'c': 3, 'n': 'Me'}, {'c': 2, 'n': 'yourself'}, {'c': 2, 'n': 'thee'}, {'c': 1, 'n': 'i"feu'}, {'c': 1, 'n': 'thy'}, {'c': 1, 'n': 'Your'}, {'c': 1, 'n': 'ray'}]})

       COREF  start_token  end_token  prop  cat           text
74702   2862       422728     422729  PROP  PER  Darling Rosey
74704   2862       422741     422741  PRON  PER            her
74835   2862       423544     423544  PROP  PER          Rosey
74836   2862       423550     423550  PRON  PER            She
74837   2862       423560     423560  PRON  PER            her
74838   2862       423567     423567  PRON  PER            her
74839   2862       423573     423573  PRON  PER            She
74840   2862       423579     423579  PRON  PER            her
74842   2862       423582     423582  PRON  PER            her

In [18]:
meta_book["characters"][887]["id"]

2862

In [17]:
meta_book["characters"][887]["g"]

{'inference': {'he/him/his': 0.225,
  'she/her': 0.693,
  'they/them/their': 0.05,
  'xe/xem/xyr/xir': 0.016,
  'ze/zem/zir/hir': 0.016},
 'argmax': 'she/her',
 'max': 0.693,
 'total': 12.651}

In [16]:
meta_book["characters"][887]["mentions"]

{'proper': [{'c': 1, 'n': 'Darling Rosey'}, {'c': 1, 'n': 'Rosey'}],
 'common': [],
 'pronoun': [{'c': 5, 'n': 'her'}, {'c': 2, 'n': 'She'}]}

In [27]:
entity_to_g[2862]

{'inference': {'he/him/his': 0.225,
  'she/her': 0.693,
  'they/them/their': 0.05,
  'xe/xem/xyr/xir': 0.016,
  'ze/zem/zir/hir': 0.016},
 'argmax': 'she/her',
 'max': 0.693,
 'total': 12.651}

In [33]:
from fashion.sources import HathiAll

In [39]:
book_id = "chi.14533347.clean"
tokens_book = pd.read_csv(
    booknlp_dir / f"{book_id}/{book_id}.tokens",
    sep="\t",
    quoting=3,  # 3 = csv.QUOTE_NONE
).set_index("token_ID_within_document")

# calculate sentence start and end indices
tokens_book["sentence_start"] = tokens_book.groupby(
    "sentence_ID"
).byte_onset.transform("min")
tokens_book["sentence_end"] = tokens_book.groupby(
    "sentence_ID"
).byte_offset.transform("max")

tokens_book["sentence_has_adjectives"] = tokens_book.groupby(
    "sentence_ID"
).POS_tag.transform(lambda x: x.eq("ADJ").any())

# get character mentions
entities_book = pd.read_csv(
    booknlp_dir / f"{book_id}/{book_id}.entities", sep="\t", quoting=3
)

meta_book = json.load(open(booknlp_dir / f"{book_id}/{book_id}.book"))
entity_to_g = {
    entity["id"]: entity["g"]
    for entity in meta_book["characters"]
    if entity["g"] is not None
}

# merge character mentions with token offsets
entities_book = entities_book.merge(
    tokens_book[["byte_onset", "sentence_start", "sentence_has_adjectives"]],
    left_on="start_token",
    right_index=True,
)
entities_book = entities_book.merge(
    tokens_book[["byte_offset", "sentence_end"]],
    left_on="end_token",
    right_index=True,
)
entities_book = entities_book.rename(
    columns={
        "byte_onset": "entity_start_idx",
        "byte_offset": "entity_end_idx",
    }
)

entities_book = entities_book[
    # entities_book.COREF.astype(str).isin(entity_corefs)
    True
    & entities_book.sentence_has_adjectives
    & entities_book.cat.eq("PER")
]
# filename,sentence,term,start_idx,end_idx,sentence_start_idx,sentence_end_idx

book = HathiAll().load_text(book_id)

if entities_book.empty:
    print(f"No entities found for book {book_id}. Skipping.")

try:
    entities_book["sentence"] = entities_book[
        ["sentence_start", "sentence_end"]
    ].apply(lambda x: book.text[x.sentence_start : x.sentence_end], axis=1)
except Exception as e:
    print(f"Error processing book {book_id}: {e}")

entities_book["term"] = entities_book[
    ["entity_start_idx", "entity_end_idx"]
].apply(lambda x: book.text[x.entity_start_idx : x.entity_end_idx], axis=1)

entities_book = entities_book.drop_duplicates(subset=["COREF", "sentence"])

output_df = pd.DataFrame(
    {
        "mention_id": entities_book.COREF,
        "filename": book_id,
        "sentence": entities_book.sentence,
        "term": entities_book.term,
        "start_idx": entities_book.entity_start_idx
        - entities_book.sentence_start,
        "end_idx": entities_book.entity_end_idx - entities_book.sentence_start,
        "sentence_start_idx": entities_book.sentence_start,
        "sentence_end_idx": entities_book.sentence_end,
        "gender": entities_book.COREF.apply(
            lambda x: entity_to_g[x]["argmax"] if x in entity_to_g else None
        ),
    }
)

In [40]:
entities_book[entities_book.COREF.eq(209)]

,COREF,start_token,end_token,prop,cat,text,entity_start_idx,sentence_start,sentence_has_adjectives,entity_end_idx,sentence_end,sentence,term
2884,209,26297,26297,PROP,PER,SNOWDROP,114763,114568,True,114771,114772,"My ladies stared, and not a word \nDid they ad...",SNOWDROP
2885,209,26300,26301,PROP,PER,Miss Snowdrop,114780,114774,True,114793,114865,ITTLE Miss Snowdrop \nHas come over the way; \...,Miss Snowdrop
2892,209,26371,26373,PROP,PER,Little Miss Snowdrop,115091,115091,True,115111,115240,"Little Miss Snowdrop, \nSo brave and so true, ...",Little Miss Snowdrop
2896,209,26426,26426,PRON,PER,her,115314,115267,True,115317,115354,"COME, little bee, to the wild rose cup; \nBrin...",her
2906,209,26595,26595,PRON,PER,her,116128,116107,True,116131,116228,"Then wild rose swung her censer, \nAnd, in a s...",her

In [41]:
output_df[output_df.mention_id.eq(209)]

,mention_id,filename,sentence,term,start_idx,end_idx,sentence_start_idx,sentence_end_idx,gender
2884,209,chi.14533347.clean,"My ladies stared, and not a word \nDid they ad...",SNOWDROP,195,203,114568,114772,she/her
2885,209,chi.14533347.clean,ITTLE Miss Snowdrop \nHas come over the way; \...,Miss Snowdrop,6,19,114774,114865,she/her
2892,209,chi.14533347.clean,"Little Miss Snowdrop, \nSo brave and so true, ...",Little Miss Snowdrop,0,20,115091,115240,she/her
2896,209,chi.14533347.clean,"COME, little bee, to the wild rose cup; \nBrin...",her,47,50,115267,115354,she/her
2906,209,chi.14533347.clean,"Then wild rose swung her censer, \nAnd, in a s...",her,21,24,116107,116228,she/her